version: '3.8'

services:
  php:
    build:
      context: ./php
    user: "1000:1000" #Fix permission errors
    volumes:
      - ./app:/var/www/app
  db:
    image: mysql:8.0
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: vektor_root
      MYSQL_DATABASE: vektorprogrammet
      MYSQL_USER: vektor
      MYSQL_PASSWORD: vektor
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '80:80'
    volumes:
      - ./app:/var/www/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db
